- name: Download tarballs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Download ZooKeeper 3.4.6
    get_url: url=http://apache.osuosl.org/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz dest=download/zookeeper-3.4.6.tar.gz
  - name: Download Storm 0.9.1
    get_url: url=https://dl.dropboxusercontent.com/s/tqdpoif32gufapo/storm-0.9.0.1.tar.gz dest=download/storm-0.9.0.1.tar.gz
  - name: Download Kafka 0.8.1
    get_url: url=http://mirror.olnevhost.net/pub/apache/kafka/0.8.1/kafka_2.9.2-0.8.1.tgz dest=download/kafka_2.9.2-0.8.1.tgz
  - name: Download Hadoop 1.2.1
    get_url: url=http://www.dsgnwrld.com/am/hadoop/common/hadoop-1.2.1/hadoop-1.2.1-bin.tar.gz dest=download/hadoop-1.2.1-bin.tar.gz
  - name: Download Cassandra 2.0.7
    get_url: url=http://mirror.reverse.net/pub/apache/cassandra/2.0.7/apache-cassandra-2.0.7-bin.tar.gz dest=download/apache-cassandra-2.0.7-bin.tar.gz
  - name: Download Leiningen script
    get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein dest=download/lein
